# This file was generated by Claude AI to help me get realistic inertial values since I chose to implement an URDF myself.

def sphere_inertia(mass, radius):
    i = (2/5) * mass * radius**2
    return {
        'ixx': i,
        'iyy': i,
        'izz': i
    }

def cylinder_inertia(mass, radius, length):
    # For cylinder along z-axis
    ixx_iyy = (1/12) * mass * (3*radius**2 + length**2)
    izz = (1/2) * mass * radius**2
    return {
        'ixx': ixx_iyy,
        'iyy': ixx_iyy,
        'izz': izz
    }

# Example for your wheel
wheel = sphere_inertia(mass=1.0, radius=0.4)
print("Wheel inertia:", wheel)

# Example for your axle
axle = cylinder_inertia(mass=1.0, radius=0.1, length=0.8)
print("Axle inertia:", axle)